export {
  REGISTRY,
  DO_NOT_TRACK,
  type RegistryEntry,
  type OptOutEntry,
  type OptInEntry,
  type UnsupportedEntry,
  type EnvOptOut,
} from "./registry.ts";
export {
  scan,
  evaluate,
  planInit,
  applyInit,
  initCommentBlock,
  parseEnvFile,
  loadEnvFile,
  loadProjectEnv,
  readDeps,
  isInstalled,
  failsCheck,
  filterResults,
  matchesIgnore,
  resolveEnv,
  resolveEnvBinding,
  type LibraryResult,
  type Status,
  type InitPlanItem,
  type InitTarget,
  type ScanOptions,
  type PlanInitOptions,
  type ApplyInitOptions,
  type ApplyInitResult,
  type EnvBinding,
  type EnvSource,
  type FilterOptions,
} from "./core.ts";
export {
  buildReport,
  buildErrorReport,
  summarize,
  toLibraryReport,
  planToActions,
  type ReportV1,
  type ReportSummary,
  type LibraryReport,
  type ReportAction,
  type ReportVersion,
} from "./report.ts";
